version: '3.9'

services:
  pytorch:
    build:
      context:  .
      dockerfile: Dockerfile
      args:
        USERNAME: user
    container_name: pytorch
    restart: always
    volumes:
      - ../:/root
    ports:
      - "2626:22"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]